#!/usr/bin/env sh

config="$1"
shift

for file in "$@" ; do
	oldkey="$(basename "$file")"
	newkey="$(ipfs add "$file" 2>/dev/null | cut -d' ' -f2)"
	echo "replacing $oldkey by $newkey in $config"
	sed "s/$oldkey/$newkey/g" -i "$config"
done
